insert into authors (id, first_name, last_name) values (1, 'Constantino', 'Gravy');
insert into authors (id, first_name, last_name) values (2, 'Bennie', 'Clarke-Williams');
insert into authors (id, first_name, last_name) values (3, 'Norrie', 'Vidler');
insert into authors (id, first_name, last_name) values (4, 'Pepita', 'Cozby');
insert into authors (id, first_name, last_name) values (5, 'Anetta', 'Pheby');
insert into authors (id, first_name, last_name) values (6, 'Pennie', 'Binnell');
insert into authors (id, first_name, last_name) values (7, 'Alejoa', 'Pressdee');
insert into authors (id, first_name, last_name) values (8, 'Frederich', 'Petit');
insert into authors (id, first_name, last_name) values (9, 'Farica', 'Thorington');
insert into authors (id, first_name, last_name) values (10, 'Vernice', 'Reynish');
insert into authors (id, first_name, last_name) values (11, 'Hervey', 'Beardon');
insert into authors (id, first_name, last_name) values (12, 'Sukey', 'Havercroft');
insert into authors (id, first_name, last_name) values (13, 'Reamonn', 'Poxon');
insert into authors (id, first_name, last_name) values (14, 'Antonin', 'Samudio');
insert into authors (id, first_name, last_name) values (15, 'Jeanie', 'Santoro');
insert into authors (id, first_name, last_name) values (16, 'Lurline', 'Muscott');
insert into authors (id, first_name, last_name) values (17, 'Gerry', 'Borrows');
insert into authors (id, first_name, last_name) values (18, 'Marya', 'Eckart');
insert into authors (id, first_name, last_name) values (19, 'Doreen', 'Roblou');
insert into authors (id, first_name, last_name) values (20, 'Alano', 'Layus');
insert into authors (id, first_name, last_name) values (21, 'Luise', 'Cunradi');
insert into books (id, price, price_old, title, author_id) values (1, 2214, 2946, 'Treeflex', 11);
insert into books (id, price, price_old, title, author_id) values (2, 2120, 1840, 'Konklux', 8);
insert into books (id, price, price_old, title, author_id) values (3, 1881, 2063, 'Mat Lam Tam', 6);
insert into books (id, price, price_old, title, author_id) values (4, 2516, 1800, 'Bytecard', 12);
insert into books (id, price, price_old, title, author_id) values (5, 1054, 3168, 'Holdlamis', 3);
insert into books (id, price, price_old, title, author_id) values (6, 1773, 2087, 'Sonsing', 19);
insert into books (id, price, price_old, title, author_id) values (7, 2726, 1791, 'Asoka', 19);
insert into books (id, price, price_old, title, author_id) values (8, 1494, 3973, 'Konklab', 8);
insert into books (id, price, price_old, title, author_id) values (9, 2178, 3640, 'Namfix', 2);
insert into books (id, price, price_old, title, author_id) values (10, 2637, 3522, 'Hatity', 13);
insert into books (id, price, price_old, title, author_id) values (11, 1629, 2018, 'Span', 7);
insert into books (id, price, price_old, title, author_id) values (12, 1314, 3347, 'Zoolab', 5);
insert into books (id, price, price_old, title, author_id) values (13, 2026, 1473, 'Lotstring', 17);
insert into books (id, price, price_old, title, author_id) values (14, 1064, 3877, 'Transcof', 18);
insert into books (id, price, price_old, title, author_id) values (15, 2835, 3167, 'Alphazap', 4);
insert into books (id, price, price_old, title, author_id) values (16, 756, 2487, 'Bitwolf', 21);
insert into books (id, price, price_old, title, author_id) values (17, 2371, 2962, 'Rank', 8);
insert into books (id, price, price_old, title, author_id) values (18, 2905, 1264, 'Voltsillam', 18);
insert into books (id, price, price_old, title, author_id) values (19, 544, 1834, 'Alphazap', 19);
insert into books (id, price, price_old, title, author_id) values (20, 1110, 2953, 'Stim', 18);
insert into books (id, price, price_old, title, author_id) values (21, 938, 1205, 'Transcof', 17);